import type { Metadata } from 'next';
import './globals.css';
import Header from '@/components/layouts/HomeLayout/Header';
import { Bevan, Epilogue } from 'next/font/google'

const epilogue = Epilogue({
  subsets: ['latin'],
  variable: '--font-epilogue',
  weight: '400' // or other weights
})

const bevan = Bevan({
  subsets: ['latin'],
  variable: '--font-bevan',
  weight: '400'
})


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${epilogue.variable} ${bevan.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
